# Site settings
title: afalkear
email: ""
description: > # this means to ignore newlines until "baseurl:"
  My not-yet-ready site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://afalkear.github.io/" # the base hostname & protocol for your site
twitter_username: afalkear
github_username:  afalkear

# Build settings
markdown: kramdown
